UPSTREAM: drm/amdgpu: Clean up errors in ppatomctrl.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 78223350126018aa159890ff1c06c747beb7d909)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I6563f372d8395d59c38e48413b6727cfb14e56bc