BACKPORT/UPSTREAM: drm/amdgpu: Fix style issues in amdgpu_gem.c
Fixes the following to align to linux coding style:

WARNING: braces {} are not necessary for any arm of this statement
WARNING: Missing a blank line after declarations
ERROR: space prohibited before that close parenthesis ')'
WARNING: unnecessary whitespace before a quoted newline
WARNING: %LX is non-standard C, use %llX

Cc: Christian König <christian.koenig@amd.com>
Cc: Alex Deucher <alexander.deucher@amd.com>
Signed-off-by: Srinivasan Shanmugam <srinivasan.shanmugam@amd.com>
Reviewed-by: Alex Deucher <alexander.deucher@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 30953c4d000b6742eeb9cb248e737ecacf3a3b96)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

Downstream changes:
  Dropped some changes to code that was moved in a previous forklift
  change.

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I0191db78b46f0fa72427ba23c81ac291a0b20e3b