UPSTREAM: drm/i915: Add __rcu annotation to cursor when iterating client objects
__rcu annotation is needed to avoid the sparse warnings such as:

  .../i915_drm_client.c:92:9: sparse: sparse: incompatible types in comparison expression (different address spaces):
  .../i915_drm_client.c:92:9: sparse:    struct list_head [noderef] __rcu *
  .../i915_drm_client.c:92:9: sparse:    struct list_head *

Signed-off-by: Tvrtko Ursulin <tvrtko.ursulin@intel.com>
Fixes: 968853033d8a ("drm/i915: Implement fdinfo memory stats printing")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202311110610.h0m6ydI5-lkp@intel.com/
Cc: Andi Shyti <andi.shyti@linux.intel.com>
Cc: Aravind Iddamsetty <aravind.iddamsetty@intel.com>
Reviewed-by: Jani Nikula <jani.nikula@intel.com>
Reviewed-by: Andi Shyti <andi.shyti@linux.intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20231113085457.199053-2-tvrtko.ursulin@linux.intel.com
(cherry picked from commit e31b380741bfa27d274a9f9610fd732e1204ea24)

BUG=b:284181254
TEST=build dedede

Signed-off-by: Rob Clark <robdclark@chromium.org>
Change-Id: Ifd9a1ae32be75e1dfd81de28378a1bf17a05c628
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5278902
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Matt Turner <msturner@google.com>