UPSTREAM: drm/amdgpu: Clean up errors in vega20_ih.c
Fix the following errors reported by checkpatch:

ERROR: trailing statements should be on next line
ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 1f45f1c592401073a93bb39eda98ba215edb6b8d)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I1c7b3c5f16176409d58bc83a4bf43d426992b2f0