UPSTREAM: drm/amdgpu: Clean up errors in uvd_v7_0.c
Fix the following errors reported by checkpatch:

ERROR: spaces required around that ':' (ctx:VxE)
that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit a788b54f3d1d0fd04da7bd422d2f7abda508c7b1)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Id6d136e1ec113b4a742243fefca69c9a8f384d19