Revert "FIXUP: FROMGIT: ANDROID: usb: f_accessory: Check buffer size when initialised via composite"
This reverts commit a5433cbfd563ae4d8c6f9f5fb387495e47f177e4.

The fixup didn't fix all compilation errors regarding to the commit.
There are some remaining:
../drivers/usb/gadget/function/f_accessory.c:965:5: error: no previous prototype for ‘acc_ctrlrequest’ [-Werror=missing-prototypes]
  965 | int acc_ctrlrequest(struct usb_composite_dev *cdev,
      |     ^~~~~~~~~~~~~~~
../drivers/usb/gadget/function/f_accessory.c:1421:6: error: no previous prototype for ‘acc_disconnect’ [-Werror=missing-prototypes]
 1421 | void acc_disconnect(void)
      |      ^~~~~~~~~~~~~~
../drivers/usb/gadget/function/f_accessory.c:1526:5: error: no previous prototype for ‘acc_ctrlrequest_configfs’ [-Werror=missing-prototypes]
 1526 | int acc_ctrlrequest_configfs(struct usb_function *f,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~

Revert the fixup, and refix the compilation errors by declaring the
symbols in header in later commits.

BUG=b:291009612
BUG=b:271919375,b:227610040
TEST=CQ

Change-Id: I093784718810f4a477290bfdd6d11f502134d121
Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4805764
Reviewed-by: Guenter Roeck <groeck@chromium.org>