UPSTREAM: drm/amd/pm: Clean up errors in vega10_pptable.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 1f9f09da7202dd76d16f7a1dab57d925c1092b9c)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I3326bac8437c1d55b07346a508aff94cf66015d8