UPSTREAM: drm/radeon: add missing spaces after ',' and else should follow close brace '}'
ERROR: else should follow close brace '}'

ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit dc2003560ced79237399193bb411e8899ec1ea3f)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ibfe898ed402c226ddd5e55e404169e344de8966f