UPSTREAM: fbdev: fbmem: mark get_fb_unmapped_area() static
There is a global function with this name on sparc, but no
global declaration:

drivers/video/fbdev/core/fbmem.c:1469:15: error: no previous prototype for 'get_fb_unmapped_area'

Make the generic definition static to avoid this warning. On
sparc, this is never seen.

Edit by Helge:
Update Kconfig text as suggested by Geert Uytterhoeven.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Helge Deller <deller@gmx.de>
(cherry picked from commit 19abb4583d5eba06459930932e72c862a83cd9c2)

BUG=b:323757777
TEST=cq dry run

Change-Id: Ida5da7d85e9604f87e78635ca46da267b873d775
Signed-off-by: Drew Davenport <ddavenport@chromium.org>