UPSTREAM: ASoC: nau8825: fix bounds check for adc_delay
clang build reports
sound/soc/codecs/nau8825.c:2826:31: error: overlapping comparisons
  always evaluate to false [-Werror,-Wtautological-overlap-compare]
        if (nau8825->adc_delay < 125 && nau8825->adc_delay > 500)
            ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

This is a bug, a logical-or should have been used.

Fixes: fc0b096c9291 ("ASoC: nau8825: Add delay control for input path")

BUG=b:250468116
TEST=The property have the expected effect.

Change-Id: Ide1280b0091209eb4094282596f4a36648dc2751
Signed-off-by: Tom Rix <trix@redhat.com>
Acked-by: David Lin <CTLIN0@nuvoton.com>
Link: https://lore.kernel.org/r/20230418120955.3230705-1-trix@redhat.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 5f3d94eb7ae877430d9fe6a9aae7dcef6c3e5fea
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)
Signed-off-by: David Lin <ctlin0@nuvoton.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4464699
Reviewed-by: Sean Paul <sean@poorly.run>
Commit-Queue: Ching Yun Chang <whalechang@google.com>
Reviewed-by: Ching Yun Chang <whalechang@google.com>