UPSTREAM: drm/amdgpu: Clean up errors in tonga_ih.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 7bb8c4f6a40d232f4d1501953a94ce4b31033c04)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Idec798f787c15499a7a0336fec96343056fa28c0