UPSTREAM: drm/amd/display: Clean up errors in dcn10_dpp_dscl.c
Fix the following errors reported by checkpatch:

ERROR: else should follow close brace '}'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 82a72b1606b1b746d1094f7734dd232527a48e28)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I072191738a42e692102299beb712173022cf55a3