UPSTREAM: drm/amd/pm: Clean up errors in vega12_hwmgr.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following enum go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 485e3fe8636b920859d5362d0ef05debbd0c1da5)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I88a84fc9289a05b295c7ef19c05956435af64a39