UPSTREAM: drm/amdgpu: Clean up errors in common_baco.c
Fix the following errors reported by checkpatch:

ERROR: code indent should use tabs where possible

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit df70be37ef74784f1b872c0c2b4d220347302356)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I86128c6ff9f2f15046332337c7bda57d74a2c3fe