UPSTREAM: drm/jpeg: Clean up errors in jpeg_v2_0.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 7c29b402368051331e75ecedc72eb988b03904b9)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I5f94cce0f2f3b202ee75c60c26804556d88b51da