CHROMIUM: soc: mediatek: Fix seq_putc() call in mtk_apu_hw_logger_seq_show()
When building with a version of clang that has -Wint-conversion as a
hard error, the build fails with:

  drivers/soc/mediatek/apusys/mtk_apu_hw_logger.c:852:16: error: incompatible pointer to integer conversion passing 'char[2]' to parameter of type 'char' [-Wint-conversion]
    852 |                         seq_putc(s, "\n");
        |                                     ^~~~
  include/linux/seq_file.h:120:40: note: passing argument to parameter 'c' here
    120 | void seq_putc(struct seq_file *m, char c);
        |                                        ^
  1 error generated.

This call should have used single quotes for the newline character,
rather than double quotes, which is a character array of the newline
character and NUL.

BUG=None
TEST=build chromiumos-arm64.flavour before and after change

Fixes: f089a6758fa92 ("CHROMIUM: soc: mediatek: apu: Add apu hardware logger dirver")
Change-Id: I406e64f2fa588eba543e47e8c94efbc8561bfc5f
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5410370
Commit-Queue: Chen-Yu Tsai <wenst@google.com>
Tested-by: Chen-Yu Tsai <wenst@google.com>
Reviewed-by: Chen-Yu Tsai <wenst@google.com>