UPSTREAM: ASoC: amd: acp: Add new cpu dai's in machine driver
when using same cpu dai for 2 different dai links
below error is reported.
error: can't find BE for DAI ACPHS_VIRTUAL1.OUT

To avoid this error add new cpu dai.

Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Link: https://lore.kernel.org/r/20230109132104.1259479-2-venkataprasad.potturu@amd.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 099b923fc15d8faa91c5fc1b46cbc483d034f5dc)

BUG=b:290189450
TEST=TESTED on myst

Change-Id: Ie60a532b514b1698cae78c9e5a69bec63d9cd2b2
Signed-off-by: V sujith kumar Reddy <vsujithkumar.reddy@amd.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4672727
Tested-by: Baili Deng <bailideng@google.com>
Commit-Queue: Baili Deng <bailideng@google.com>
Reviewed-by: Baili Deng <bailideng@google.com>
Reviewed-by: Sean Paul <sean@poorly.run>