UPSTREAM: drm/amdgpu: Clean up errors in smu7_powertune.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 4e01bbec4b318ebf8619dfd5e7c9fcb5fef511a2)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I9ecc17173f3a01c7da996811c53b79f6a95d33b3