UPSTREAM: drm/radeon: Move assignment outside if condition
Fixes the following checkpatch errors:

ERROR: do not use assignment in if condition

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 819362e4e62787343d986c5d5701121eeee60eab)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I1a1f00cb6dc933f00e5d7bb25596b12d0ab8be91