UPSTREAM: drm/amd/pm: Clean up errors in vega12_hwmgr.c
Fix the following errors reported by checkpatch:

ERROR: need consistent spacing around '/' (ctx:WxV)
ERROR: code indent should use tabs where possible

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 28b3a7330c52f8d588a5207e2d26d86f9ffb58b8)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I5b70e8762cd7bfcdc8a1eb2305cb2cc45f5d4a9c