FIXUP: CHROMIUM: drm/evdi: Port evdi from github.com/DisplayLink/evdi.git
0-day errors:
>> drivers/gpu/drm/evdi/evdi_gem.c:278:25: error: implicit
   declaration of function 'vmap'
>> drivers/gpu/drm/evdi/evdi_gem.c:301:17: error: implicit
   declaration of function 'vunmap'
>> drivers/gpu/drm/evdi/evdi_drm_drv.h: drm/drm_framebuffer.h
   is included more than once.

Adding missing header file vmalloc.h and remove duplicate include.

BUG=b:250914045,b:227610040
TEST=Build and test on trogdor and sarien boards

Change-Id: I66cb2f76bdcbca7fb2a04043bd60ffb9070a7e63
Signed-off-by: Aashish Sharma <shraash@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4559848
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>