UPSTREAM: drm/amd/pm: Clean up errors in vega12_baco.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit cbe2d154aa3a2384144af388371f3acc2b364cdb)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ica5996fa6330990235100d7ddb35b2e2bcec17af