BACKPORT: drm/amd/display: fix dp_retrieve_lttpr_cap() return value
gcc-13 notices a mismatch between the return type of dp_retrieve_lttpr_cap()
and the returned value:

drivers/gpu/drm/amd/amdgpu/../display/dc/link/link_dp_capability.c: In function 'dp_retrieve_lttpr_cap':
drivers/gpu/drm/amd/amdgpu/../display/dc/link/link_dp_capability.c:1465:24: error: implicit conversion from 'enum <anonymous>' to 'enum dc_status' [-Werror=enum-conversion]
 1465 |                 return false;
      |                        ^~~~~

Change the value to an actual dc_status code and remove the bogus
initialization that was apparently meant to get returned here.

Fixes: b473bd5fc333 ("drm/amd/display: refine wake up aux in retrieve link caps")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>

Conflicts: dp_retrieve_lttpr_cap function was moved to a new file further
  upstream.

(cherry picked from commit 5e3ec82c0243f77e31c3ce6ccbf722cb96db0cee)

Conflicts:
   drivers/gpu/drm/amd/display/dc/link/link_dp_capability.c

BUG=b:270590111
TEST=build test

Change-Id: I06ac9fcbb12f5a800b9dcdc4ba3b988262c89c31
Signed-off-by: Drew Davenport <ddavenport@chromium.org>