UPSTREAM: drm/amd/pm: Clean up errors in hwmgr.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line
ERROR: Use C99 flexible arrays

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 6f569e69317e411765b3d02ec9dd6e6c7b816321)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ia5b651ccedfd0b8967c0b67f684fb2ae25c485d5