FIXUP: drm/i915/mtl: Add support for PM DEMAND
0-day errors:

>> drivers/gpu/drm/i915/display/intel_pmdemand.h:36:17:
   error: use of undeclared identifier 'I915_MAX_PIPES'
>> drivers/gpu/drm/i915/display/intel_pmdemand.h:55:16:
   error: declaration of 'enum pipe' will not be visible
   outside of this function [-Werror,-Wvisibility]

Add the missing header file.

BUG=b:265114629,b:227610040
TEST=i915 driver loaded successfully

Change-Id: Ia7d6817b838d2f9937dd30eb1981079d12cdd630
Signed-off-by: Aashish Sharma <shraash@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4664024
Reviewed-by: Drew Davenport <ddavenport@chromium.org>