UPSTREAM: drm/amdgpu: Clean up errors in nv.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 939a392f07e2d553feec97d7345a054586169d0a)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Id18a257b474d9e7b5f68e819555956295e9c9b0e