UPSTREAM: drm/amdgpu/powerplay: Clean up errors in smu_helper.h
Fix the following errors reported by checkpatch:

ERROR: space prohibited before that close parenthesis ')'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 05dfc1beeb01f2f7d623c44e2b3b0d2ba034ce29)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: If0cb136ea26728fa0ac70adec51f3c9ded8f8ac3