UPSTREAM: drm/amd/display: Clean up errors in display_mode_vba_30.c
Fix the following errors reported by checkpatch:

ERROR: else should follow close brace '}'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 06788a22aa8d49efa11b6dc6eca818719de0192f)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I379cdee98025d800ad93adf78fd04a1953963d93