UPSTREAM: drm/amd/pm/powerplay/hwmgr/hwmgr: Clean up errors in hwmgr.c
Fix the following errors reported by checkpatch:

ERROR: space prohibited after that '~' (ctx:WxW)
ERROR: spaces required around that '||' (ctx:VxW)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 79501a7fb4c46e7ca35824cd7050197ff3f9d441)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I57cd59e7403bc558208fcaa6ed5f34522b4bff04