UPSTREAM: gpu: amd: Clean up errors in ppatomfwctrl.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 0abfc3fd1dda58fe6d0be71647ebdeb0f18f2e06)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Ib741cdcf3348498287a28d546a3ed9f27f1ba195