UPSTREAM: drm/amd/display: Clean up errors in color_gamma.c
Fix the following errors reported by checkpatch:

ERROR: trailing whitespace
ERROR: else should follow close brace '}'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 3646a89db179a2ff91642d26a59ca01de3ac3cd5)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I798e39eb08420c69307bbd8e832ff02d711a7418