UPSTREAM: debugfs: Fix __rcu type comparison warning
Sparse reports the following:

fs/debugfs/file.c:942:9: sparse: sparse: incompatible types in comparison expression (different address spaces):
fs/debugfs/file.c:942:9: sparse:    char [noderef] __rcu *
fs/debugfs/file.c:942:9: sparse:    char *

rcu_assign_pointer() expects that it's assigning to pointers annotated
with __rcu. We can't annotate the generic struct file::private_data, so
cast it instead.

Fixes: 86b5488121db ("debugfs: Add write support to debugfs_create_str()")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202309091933.BRWlSnCq-lkp@intel.com/
Signed-off-by: Mike Tipton <quic_mdtipton@quicinc.com>
Link: https://lore.kernel.org/r/20230922134512.5126-1-quic_mdtipton@quicinc.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 7360a48bd0f5e62b2d00c387d5d3f2821eb290ce)

BUG=b:314887266
TEST=i915 works, no driver errors, no visible issues or flickers

Change-Id: I440f26f741ac66939be7650222795e701e75f5fd
Signed-off-by: Paz Zcharya <pazz@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5263038
Tested-by: Paz Zcharya <pazz@google.com>
Commit-Queue: Paz Zcharya <pazz@google.com>
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Sarthak Kukreti <sarthakkukreti@google.com>