UPSTREAM: drm/amdgpu: Clean up errors in amdgpu_virt.c
Fix the following errors reported by checkpatch:

ERROR: space required before the open parenthesis '('

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit baa5ede87568677b6321f9559b7bc2a16acb3f10)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I305aab6356cf1f4870ffe536e5019284b548113e