UPSTREAM: drm/amd/display: Clean up errors in bios_parser2.c
Fix the following errors reported by checkpatch:

ERROR: switch and case should be at the same indent
ERROR: code indent should use tabs where possible

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 7c755e21bbc7ae3cc128eab1669b687165ca51c4)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I04fe55a8dcf6344ff4aaab99dad982198dac0346