UPSTREAM: drm/amdgpu: Clean up errors in mes_v11_0.c
Fix the following errors reported by checkpatch:

ERROR: else should follow close brace '}'

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 91aafa3c4e89509496b0d0d03f5735f1952dd5e8)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Id779d7dd1ea4da3a78996566f7fa5f48b0e40ca8