UPSTREAM: drm/amdgpu/jpeg: Clean up errors in vcn_v1_0.c
Fix the following errors reported by checkpatch:

ERROR: space required before the open parenthesis '('
ERROR: space prohibited after that '~' (ctx:WxW)

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 665ba81b4a0c3776f3161e5ab35d93ab9e4740c7)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I266c02107103c51e017e93aa8f8205699e962f0c