UPSTREAM: drm/amdgpu: Clean up errors in ci_baco.c
Fix the following errors reported by checkpatch:

ERROR: that open brace { should be on the previous line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 958f27fc528a866027de7b7c01c59108fe0700bc)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I075c9a038dc0d63058ecf6ae3c354713d337eb54