UPSTREAM: drm/radeon: ERROR: "(foo*)" should be "(foo *)"
Fix five occurrences of the checkpatch.pl error:
ERROR: "(foo*)" should be "(foo *)"

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit b82dc4ed4060a80547fdfbf266912462cbc06ab2)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: Iaca9cff2c3d968056009f0d9bbdd04f6d0a844d2