UPSTREAM: drm/amd/pm: Clean up errors in pp_thermal.h
Fix the following errors reported by checkpatch:

ERROR: open brace '{' following struct go on the same line

Signed-off-by: Ran Sun <sunran001@208suo.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 4d2d4f151baa7a91796c91e77d93f6904297cb2f)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=323757777
TEST=cq dry run

Backported using forklift.py

Change-Id: I897b0af7ea8c727d8e0da8bf3a419ce0389f451a