BACKPORT: FROMGIT: drm/i915/hdcp: Fail Repeater authentication if Type1 device not present
Fail repeater authentication step in case RX_INFO indicates
HDCP1.x or HDCP2.0/2.1 device is present downstream in repeater
topology and content type set by userspace is Type1.

--v2
-Fix build error.

--v3
-remove mst encoder check as branch device also act as repeater

Signed-off-by: Suraj Kandpal <suraj.kandpal@intel.com>
Reviewed-by: Ankit Nautiyal <ankit.k.nautiyal@intel.com>
Signed-off-by: Ankit Nautiyal <ankit.k.nautiyal@intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20231215050915.2070119-1-suraj.kandpal@intel.com
(cherry picked from commit da2d668480c37d43a423ff7822caba2e0c58c4ac
 https://anongit.freedesktop.org/git/drm-intel drm-intel-next)
Backport notes:
	This fix addresses the compilation error "drivers/gpu/drm/i915/display/intel_hdcp.c"
	error: use of undeclared identifier 'i915' in drm_dbg_kms,
	So, changed &i915->drm to &dev_priv->drm.

BUG=b:318780360
TEST=External display Hot-Plug while play Netflix/Prime video should work fine

Change-Id: I046325812113d5245834b220adbb89e5f4ea1570
Signed-off-by: Rakshith M O <rakshith.m.o@intel.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5173391
Reviewed-by: Drew Davenport <ddavenport@chromium.org>
Tested-by: Shantam Yashashvi <shantam.yashashvi@intel.corp-partner.google.com>